import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";

export const metadata = {
  title: "Terms of Service — Validue",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="bg-[#1C1917] text-white min-h-screen">
        <div className="max-w-[720px] mx-auto px-[64px] max-md:px-[24px] pt-[120px] pb-[80px]">
          <span className="font-mono text-[11px] font-medium tracking-wide text-[#78716C] uppercase block mb-[8px]">
            Legal
          </span>
          <h1 className="text-[32px] font-medium tracking-tight mb-[8px]">Terms of Service</h1>
          <p className="font-mono text-[11px] text-[#78716C] uppercase tracking-wide mb-[48px]">
            Effective: April 3, 2026
          </p>

          <div className="prose-legal">
            <Section title="1. Acceptance of Terms">
              <p>
                By accessing or using Validue (&quot;the Platform&quot;), operated by Validue Inc.
                (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;), you agree to be bound by these Terms of
                Service. If you do not agree, do not use the Platform.
              </p>
            </Section>

            <Section title="2. Eligibility">
              <p>
                You must be at least 18 years old and capable of forming a binding contract.
                By creating an account, you represent that you meet these requirements.
              </p>
            </Section>

            <Section title="3. Accounts">
              <p>
                You are responsible for maintaining the confidentiality of your account credentials
                and for all activity under your account. You must provide accurate information
                during registration and keep it current. You may not create multiple accounts
                or share account access.
              </p>
            </Section>

            <Section title="4. Platform Description">
              <p>
                Validue is an assumption-testing platform. Founders (&quot;Creators&quot;) post
                campaigns describing startup ideas. Respondents provide feedback on those campaigns.
                AI systems score, rank, and synthesize responses into Decision Briefs for Creators.
              </p>
            </Section>

            <Section title="5. Creator Responsibilities">
              <p>
                Creators must provide truthful campaign descriptions. Campaigns must not contain
                illegal content, hate speech, harassment, or personally identifiable information
                about third parties. We reserve the right to remove campaigns that violate these
                standards without refund.
              </p>
            </Section>

            <Section title="6. Respondent Responsibilities">
              <p>
                Respondents must provide honest, original feedback. Automated responses, copy-pasted
                content, and deliberately low-effort submissions may be disqualified. Disqualified
                responses do not earn payouts. Respondents must not submit responses to their own
                campaigns.
              </p>
            </Section>

            <Section title="7. Payments & Payouts">
              <p>
                Campaign funding is processed via Stripe. Funded amounts are non-refundable once a
                campaign is published and receives responses. Respondent payouts are calculated based
                on response quality scores determined by our AI systems. Payout amounts are at our
                discretion based on the published payout model.
              </p>
              <p>
                Respondents may cash out available balances to their connected bank account via
                Stripe Connect, subject to a minimum cashout threshold. We are not responsible for
                delays caused by Stripe or your financial institution.
              </p>
            </Section>

            <Section title="8. AI Systems & Scoring">
              <p>
                Response quality scores are generated by AI and may include fallback heuristics.
                Scores are provided on a best-effort basis. We do not guarantee the accuracy of
                AI-generated scores, briefs, or recommendations. Creators should use Decision Briefs
                as one input among many when making business decisions.
              </p>
            </Section>

            <Section title="9. Intellectual Property">
              <p>
                Creators retain ownership of their campaign content. Respondents retain ownership of
                their responses. By submitting content, you grant us a non-exclusive, worldwide
                license to use, display, and process that content for platform operations, including
                AI analysis and brief generation. We will not sell your individual responses to third
                parties.
              </p>
            </Section>

            <Section title="10. Prohibited Conduct">
              <p>You may not:</p>
              <ul>
                <li>Game the scoring or payout system through collusion, fake accounts, or automation</li>
                <li>Scrape, reverse-engineer, or interfere with platform operations</li>
                <li>Harass other users or submit threatening, defamatory, or illegal content</li>
                <li>Use the platform for any purpose other than its intended use</li>
                <li>Attempt to circumvent rate limits, response caps, or anti-abuse measures</li>
              </ul>
            </Section>

            <Section title="11. Account Termination">
              <p>
                We may suspend or terminate your account for violation of these terms, suspected
                fraud, or at our discretion. You may delete your account at any time through your
                settings page. Upon deletion, your data will be removed in accordance with our
                Privacy Policy. Pending payouts will be forfeited if your account is terminated
                for cause.
              </p>
            </Section>

            <Section title="12. Disclaimer of Warranties">
              <p>
                The Platform is provided &quot;as is&quot; and &quot;as available&quot; without
                warranties of any kind, express or implied. We do not guarantee uninterrupted
                service, accuracy of AI outputs, or specific payout amounts.
              </p>
            </Section>

            <Section title="13. Limitation of Liability">
              <p>
                To the maximum extent permitted by law, Validue Inc. shall not be liable for any
                indirect, incidental, special, consequential, or punitive damages arising from your
                use of the Platform. Our total liability shall not exceed the amount you paid to us
                in the 12 months preceding the claim.
              </p>
            </Section>

            <Section title="14. Dispute Resolution">
              <p>
                Any disputes shall be resolved through binding arbitration in accordance with the
                rules of the American Arbitration Association. You waive any right to participate
                in a class action. For payout disputes, you may contact us at
                support@validue.com and we will review within 14 business days.
              </p>
            </Section>

            <Section title="15. Changes to Terms">
              <p>
                We may update these terms at any time. Material changes will be communicated via
                the Platform. Continued use after changes constitutes acceptance.
              </p>
            </Section>

            <Section title="16. Contact">
              <p>
                Questions about these terms? Contact us at{" "}
                <a href="mailto:legal@validue.com" className="text-[#D4A088] hover:text-white transition-colors">
                  legal@validue.com
                </a>
              </p>
            </Section>
          </div>
        </div>
        <div className="max-w-[720px] mx-auto px-[64px] max-md:px-[24px]">
          <Footer />
        </div>
      </main>
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-[32px]">
      <h2 className="text-[16px] font-medium tracking-tight text-white mb-[12px]">{title}</h2>
      <div className="text-[14px] text-[#A8A29E] leading-[1.7] font-medium [&_p]:mb-[12px] [&_ul]:list-disc [&_ul]:pl-[20px] [&_ul]:mb-[12px] [&_li]:mb-[6px]">
        {children}
      </div>
    </div>
  );
}
